version: '2'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 2181:2181
  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: my-kafka
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://my-kafka:29092,PLAINTEXT_HOST://my-kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1

  authorservice:
    depends_on: 
      - kafka
    image: adoptopenjdk/maven-openjdk11:latest
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    command: mvn spring-boot:run
    ports:
      - 8082:8082
    working_dir: /usr/src
    volumes:
      - ./authorservice:/usr/src
      - ./maven-repo:/root/.m2
      
  menuscriptservice:
    depends_on: 
      - kafka
    image: adoptopenjdk/maven-openjdk11:latest
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    command: mvn spring-boot:run
    ports:
      - 8083:8083
    working_dir: /usr/src
    volumes:
      - ./menuscriptservice:/usr/src
      - ./maven-repo:/root/.m2
      
  aiservice:
    depends_on: 
      - kafka
    image: adoptopenjdk/maven-openjdk11:latest
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    command: mvn spring-boot:run
    ports:
      - 8084:8084
    working_dir: /usr/src
    volumes:
      - ./aiservice:/usr/src
      - ./maven-repo:/root/.m2
      
  userservice:
    depends_on: 
      - kafka
    image: adoptopenjdk/maven-openjdk11:latest
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    command: mvn spring-boot:run
    ports:
      - 8085:8085
    working_dir: /usr/src
    volumes:
      - ./userservice:/usr/src
      - ./maven-repo:/root/.m2
      
  libraryservice:
    depends_on: 
      - kafka
    image: adoptopenjdk/maven-openjdk11:latest
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    command: mvn spring-boot:run
    ports:
      - 8086:8086
    working_dir: /usr/src
    volumes:
      - ./libraryservice:/usr/src
      - ./maven-repo:/root/.m2
      
  pointservice:
    depends_on: 
      - kafka
    image: adoptopenjdk/maven-openjdk11:latest
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    command: mvn spring-boot:run
    ports:
      - 8087:8087
    working_dir: /usr/src
    volumes:
      - ./pointservice:/usr/src
      - ./maven-repo:/root/.m2
      
  applyservice:
    depends_on: 
      - kafka
    image: adoptopenjdk/maven-openjdk11:latest
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    command: mvn spring-boot:run
    ports:
      - 8088:8088
    working_dir: /usr/src
    volumes:
      - ./applyservice:/usr/src
      - ./maven-repo:/root/.m2
      
